# TODO: DEBUG 
# NOT TO BE USED IN FINAL IMPLEMENTATION

# Addresses to bind to as node
address = "localhost:5683"

# Key with which to combine in the final step
# DO NOT RE-USE THIS EXAMPLE VALUE!
# Will be randomly generated in a new config file
#key = [
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#    64,
#]
tdprf_key = [107, 214, 108, 155, 178, 242, 89, 10, 92, 222, 168, 123, 162, 248, 190, 244, 70, 81, 205, 87, 60, 152, 72, 57, 15, 71, 167, 129, 93, 140, 72, 13]
aead_key = [93, 225, 12, 41, 225, 27, 201, 127, 79, 147, 154, 214, 118, 48, 143, 98]
