broker = "localhost"
clients = [
    "node0001",
    "node0002",
    "node0003",
    "node0004",
    "node0005",
    #    "node0006",
    #    "node0007",
    #    "node0008",
    #    "node0009",
    #    "node0010",
    #    "node0011",
    #    "node0012",
    #    "node0013",
    #    "node0014",
    #    "node0015",
    #    "node0016",
    #    "node0017",
]
k = 3
