# To run on a macOS
# 1. rustup target add armv7-unknown-linux-musleabihf
# 2. rustup target add arm-unknown-linux-musleabihf
# 3. Install brew install arm-linux-gnueabihf-binutils
# 4. For Pi Zero: cargo build --target arm-unknown-linux-musleabihf 
#    For Pi 2/3:  cargo build --target armv7-unknown-linux-musleabihf 

[build]

# Pi Zeros
[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"

# Pi 2/3
[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
