[package]
name = "socioty_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = { version = "0.2.139" }
rand = { version = "0.7" }
socioty = { path = "../.." }
