[package]
name = "socioty_benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7" }
socioty = { path = "../.." }
ascon-aead = { version = "0.4.0" }
