#!/bin/bash 

base_ip="128.220.247"
port="5683"
nodes=("222" "223" "224" "226" "230" "231" "242" "243" "244" "245" "246" "247")
iterations=1000
stamp=1675014677

for n in {5..12}
do
    init_config_str="clients = [\n"
    # Add correct IP addresses to init toml file. Run coap init
    for (( i=0; i<$n; i++ ))
    do
        init_config_str+="\"${base_ip}.${nodes[i]}:${port}\",\n"
    done
    init_config_str+="]\n"

    for (( t=$n-2; t<=$n; t++ ))
    do
        echo "Running: n=${n} t=${t}"
        run_dir="run_${n}_${t}"
        mkdir ${run_dir}
        echo -e "${init_config_str}k=${t}" > "${run_dir}/init_config_${n}_${t}.toml"
        cd "${run_dir}/"
        eval "/home/lkostic1/socioty-main/target/release/socioty_coap_init init_config_${n}_${t}.toml"

        #send to nodes toml files
        echo "copying files"
        for (( i=1; i<=$n; i++ ))
        do
            let j=i-1
            eval "scp ${base_ip}.${nodes[j]}_${port}_config.toml node${i}:coap/${run_dir}_node.toml"
            eval "ssh node${i} 'nohup /home/logan/coap/socioty_coap_node coap/${run_dir}_node.toml >/dev/null 2>&1 &'"
        done
        echo "copying files done"
        sleep 1

        echo "Starting iterations"
        touch ../run_${n}_${t}_output.txt
        for (( itr=0; itr<$iterations; itr++ ))
        do
            echo "Iteration${itr}: " >> ../run_${n}_${t}_output.txt
            eval "/home/lkostic1/socioty-main/target/release/socioty_coap_request request_config.toml $stamp $t >> ../run_${n}_${t}_output.txt"
        done

        echo "killing procs now"
        for (( i=1; i<=$n; i++ ))
        do
            eval "ssh node${i} './cleanup_procs socioty_coap_node'"
        done
        echo "killing procs done"
        sleep 1
        cd ..
    done
done
